### PR TITLE
new func UpgradeMode for binary mode

### PR DESCRIPTION
**Pull request by tsingson**
add websocket mode ( text or binary )  to Upgrader ,
add new func UpgradeMode for binary mode, to make sure javascript websocket support flatbuffers decode via arraybuffers

### CODE REVIEW

**Comment by dgrr** [comment]
Can you see the reviews? Please

**Comment by tsingson** [comment]
@dgrr  something wrong with me ?

**Comment by dgrr** [comment]
Hello @tsingson 

I think I opened a review process on Github right? I commented out on some parts of your code

**Comment by tsingson** [comment]
cool.

i m researching https://github.com/crossbario/autobahn-testsuite, try to to some work on fastws.

**Comment by dgrr** [comment]
@tsingson Why are you researching there? Anyway, I have a autobahn example for fastws. Let me push it.

But can you see the comments I posted in your pr?

**Comment by tsingson** [comment]
can't see comments in my PR.

**Comment by dgrr** [comment]
> can't see comments in my PR.

Now?

**Comment by tsingson** [comment]
my studio had built some  business project via golang about 4 years. And use fasthttp in those projects over 2 years.

now , a new startup project need websocket ,   android client / IOS client , so , i try fastws with more test.

**Comment by tsingson** [comment]
> > can't see comments in my PR.
> 
> Now?

maybe little later.
thanks.

**Comment by tsingson** [comment]
PR closed.
i should double check the RFC , the  rewrite my code.

**Pull request closed without merging**
